config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: 'tasks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :done)
  end

  def to_tasks_new
    redirect_to new_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :done %>
  <%= f.check_box :done %>
  <br>

  <%= f.submit 'Submit', class: "btn btn-success" %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/form.html.erb
<%= form_for(@task) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>

  <%= f.label :done %>
  <%= f.text_field :done %>
  <br>

  <%= f.submit 'Submit', class: "btn btn-success" %>
<% end %>

app/views/tasks/index.html.erb
<h1>List of Tasks</h1>
<div class="container">
  <div class="row">
    <%= @tasks.each do |task| %>
    <div class="col-xs-8 col-xs-offset-4">
      <h3><%= link_to task.name, task_path(task) %></h3>
      <h4>Done:<%= task.done %></h4>
      <%= link_to "Delete this task", task_path(task), method: "delete" %>
    </div>
    <% end %>
    <%= link_to "New", new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1> Your task: <%= @task.name %></h1>
      <h4> Done? <%= @task.done %> </h4>
    </div>
  </div>
</div>